### ISSUE TITLE
CUDA out of memory while training

### ISSUE THREAD

**Issue by WangkiShinran** [hustvl/MapTR#21]
I use 2 NVIDIA TITAN RTX 24GB GPU to train this model:
./tools/dist_train.sh ./projects/configs/maptr/maptr_nano_r18_110e.py 2
but I got CUDA out of memory while put the model to cuda

**Comment by WangkiShinran** [comment]
Here are my environment info:
------------------------------------------------------------
sys.platform: linux
Python: 3.8.16 (default, Jan 17 2023, 23:13:24) [GCC 11.2.0]
CUDA available: True
GPU 0,1: NVIDIA TITAN RTX
CUDA_HOME: /usr/local/cuda-11.3
NVCC: Build cuda_11.3.r11.3/compiler.29920130_0
GCC: gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
PyTorch: 1.9.1+cu111
PyTorch compiling details: PyTorch built with:
  - GCC 7.3
  - C++ Version: 201402
  - Intel(R) oneAPI Math Kernel Library Version 2021.4-Product Build 20210904 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v2.1.2 (Git Hash 98be7e8afa711dc9b66c8ff3504129cb82013cdb)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - CUDA Runtime 11.1
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_86,code=sm_86
  - CuDNN 8.0.5
  - Magma 2.5.2
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=11.1, CUDNN_VERSION=8.0.5, CXX_COMPILER=/opt/rh/devtoolset-7/root/usr/bin/c++, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_KINETO -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-unused-local-typedefs -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Wno-stringop-overflow, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_VERSION=1.9.1, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, 

TorchVision: 0.10.1+cu111
OpenCV: 4.7.0
MMCV: 1.4.0
MMCV Compiler: GCC 7.5
MMCV CUDA Compiler: 11.3
MMDetection: 2.14.0
MMSegmentation: 0.14.1
MMDetection3D: 0.17.2+7d100d9
------------------------------------------------------------

Thanks!

**Comment by LegendBC** [comment]
Thanks for your interest! For your case, you can reduce the batch size of MapTR-nano.

**Comment by WangkiShinran** [comment]
Thanks for your reply! Maybe it is the problem of the server itself. I changed another server and then this problem was solved.

**Comment by HongYegg** [comment]
> Thanks for your interest! For your case, you can reduce the batch size of MapTR-nano.

Can you tell me specifically where to set batchsize? My graphics card only has 2G. Thanks.
RuntimeError: CUDA out of memory. Tried to allocate 282.00 MiB (GPU 0; 1.83 GiB total capacity; 488.54 MiB already allocated; 164.94 MiB free; 520.00 MiB reserved in total by PyTorch)

**Comment by HongYegg** [comment]
> > Thanks for your interest! For your case, you can reduce the batch size of MapTR-nano.
> 
> Can you tell me specifically where to set batchsize? My graphics card only has 2G. Thanks. RuntimeError: CUDA out of memory. Tried to allocate 282.00 MiB (GPU 0; 1.83 GiB total capacity; 488.54 MiB already allocated; 164.94 MiB free; 520.00 MiB reserved in total by PyTorch)

I can't find it.

**Comment by BatyrM** [comment]
@HongYegg Try in train.py samples_per_gpu variable change. But I am not sure whether with your graphics card memory will be enough or not. You can just check.
